export const LESSON_LIST_REQUEST = 'LESSON_LIST_REQUEST';
export const LESSON_LIST_SUCCESS = 'LESSON_LIST_SUCCESS';
export const LESSON_LIST_FAILURE = 'LESSON_LIST_FAILURE';

export const LESSON_DETAILS_REQUEST = 'LESSON_DETAILS_REQUEST';
export const LESSON_DETAILS_SUCCESS = 'LESSON_DETAILS_SUCCESS';
export const LESSON_DETAILS_FAILURE = 'LESSON_DETAILS_FAILURE';

export const LESSON_DELETE_REQUEST = 'LESSON_DELETE_REQUEST';
export const LESSON_DELETE_SUCCESS = 'LESSON_DELETE_SUCCESS';
export const LESSON_DELETE_FAILURE = 'LESSON_DELETE_FAILURE';

export const LESSON_CREATE_REQUEST = 'LESSON_CREATE_REQUEST';
export const LESSON_CREATE_SUCCESS = 'LESSON_CREATE_SUCCESS';
export const LESSON_CREATE_FAILURE = 'LESSON_CREATE_FAILURE';
export const LESSON_CREATE_RESET = 'LESSON_CREATE_RESET';

export const LESSON_UPDATE_REQUEST = 'LESSON_UPDATE_REQUEST';
export const LESSON_UPDATE_SUCCESS = 'LESSON_UPDATE_SUCCESS';
export const LESSON_UPDATE_FAILURE = 'LESSON_UPDATE_FAILURE';
export const LESSON_UPDATE_RESET = 'LESSON_UPDATE_RESET';

export const LESSON_CREATE_REVIEW_REQUEST = 'LESSON_CREATE_REVIEW_REQUEST';
export const LESSON_CREATE_REVIEW_SUCCESS = 'LESSON_CREATE_REVIEW_SUCCESS';
export const LESSON_CREATE_REVIEW_FAILURE = 'LESSON_CREATE_REVIEW_FAILURE';
export const LESSON_CREATE_REVIEW_RESET = 'LESSON_CREATE_REVIEW_RESET';

export const LESSON_TOP_RATED_REQUEST = 'LESSON_TOP_RATED_REQUEST';
export const LESSON_TOP_RATED_SUCCESS = 'LESSON_TOP_RATED_SUCCESS';
export const LESSON_TOP_RATED_FAILURE = 'LESSON_TOP_RATED_FAILURE';
