export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAILURE = 'STUDENT_LOGIN_FAILURE';
export const STUDENT_LOGIN_REFRESH_REQUEST = 'STUDENT_LOGIN_REFRESH_REQUEST';
export const STUDENT_LOGIN_REFRESH_SUCCESS = 'STUDENT_LOGIN_REFRESH_SUCCESS';
export const STUDENT_LOGIN_REFRESH_FAILURE = 'STUDENT_LOGIN_REFRESH_FAILURE';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';

export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST';
export const STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS';
export const STUDENT_REGISTER_FAILURE = 'STUDENT_REGISTER_FAILURE';

export const STUDENT_RESET_PASSWORD_REQUEST = 'STUDENT_RESET_PASSWORD_REQUEST';
export const STUDENT_RESET_PASSWORD_SUCCESS = 'STUDENT_RESET_PASSWORD_SUCCESS';
export const STUDENT_RESET_PASSWORD_FAILURE = 'STUDENT_RESET_PASSWORD_FAILURE';

// To send the email verification link
export const STUDENT_EMAIL_VERIFICATION_REQUEST =
	'STUDENT_EMAIL_VERIFICATION_REQUEST';
export const STUDENT_EMAIL_VERIFICATION_SUCCESS =
	'STUDENT_EMAIL_VERIFICATION_SUCCESS';
export const STUDENT_EMAIL_VERIFICATION_FAILURE =
	'STUDENT_EMAIL_VERIFICATION_FAILURE';

// To actually verify the email token and confirm the student email
export const STUDENT_CONFIRM_REQUEST = 'STUDENT_CONFIRM_REQUEST';
export const STUDENT_CONFIRM_SUCCESS = 'STUDENT_CONFIRM_SUCCESS';
export const STUDENT_CONFIRM_FAILURE = 'STUDENT_CONFIRM_FAILURE';

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST';
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS';
export const STUDENT_DETAILS_FAILURE = 'STUDENT_DETAILS_FAILURE';
export const STUDENT_DETAILS_RESET = 'STUDENT_DETAILS_RESET';

export const STUDENT_PROFILE_UPDATE_REQUEST = 'STUDENT_PROFILE_UPDATE_REQUEST';
export const STUDENT_PROFILE_UPDATE_SUCCESS = 'STUDENT_PROFILE_UPDATE_SUCCESS';
export const STUDENT_PROFILE_UPDATE_FAILURE = 'STUDENT_PROFILE_UPDATE_FAILURE';
export const STUDENT_PROFILE_UPDATE_RESET = 'STUDENT_PROFILE_UPDATE_RESET';

export const STUDENT_LIST_REQUEST = 'STUDENT_LIST_REQUEST';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAILURE = 'STUDENT_LIST_FAILURE';
export const STUDENT_LIST_RESET = 'STUDENT_LIST_RESET';

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST';
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS';
export const STUDENT_DELETE_FAILURE = 'STUDENT_DELETE_FAILURE';

export const STUDENT_UPDATE_REQUEST = 'STUDENT_UPDATE_REQUEST';
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS';
export const STUDENT_UPDATE_FAILURE = 'STUDENT_UPDATE_FAILURE';
export const STUDENT_UPDATE_RESET = 'STUDENT_UPDATE_RESET';
